spring:
  data:
    mongodb:
      uri: mongoDB{URI}
      database: user-api
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG